### PR TITLE
fix(marble-diagrams): some images are weirds to see

### PR DESCRIPTION
**Pull request by MrJmpl3**
I need a one commit to finish my Hackoctoberfest

Looking the docs, I found a problem of visibility with the images

### CODE REVIEW

**Comment by MrJmpl3** [comment]
Missing fix some images, to see the comparison, please use Swipe Image Comparator of Github.

**Comment by MrJmpl3** [comment]
Bump @tonivj5 @Caballerog, all images was fixed, please check and accept.

And please, please add the label "hacktoberfest-accepted" in the PR to finish my Hacktoberfest

**Comment by tonivj5** [comment]
I see what you mean
image

It happens with all images :laughing: Good catch :+1:

Please @NyaGarcia, @zaldih or @Caballerog review it and add hacktoberfest's label :+1:

**Review by tonivj5 — APPROVED** [review]
I have checked some images and it looks okay :+1:

**Review by Caballerog — APPROVED** [review]

**Pull request merged**
